### 新規診断セットの作成 (POSTリクエスト)
POST http://localhost:5000/api/diagnoses
Content-Type: application/json

{
  "title": "新しい診断セットのタイトル"
}
### 診断セットの削除 (DELETEリクエスト)
DELETE http://localhost:5000/api/diagnoses/2
### 診断セットの更新 (公開に設定)
PATCH http://localhost:5000/api/diagnoses/1
Content-Type: application/json

{
  "is_public": 1
}